### ISSUE TITLE
以直线方式连接两个Node后，再选中该连线，该连线会消失！

### ISSUE THREAD

**Issue by MengxiQ** [Mirror198829/vue-topo#20]
大佬你好！我在使用该项目的使用发现一个bug： 当以直线方式连接两个Node后，再选中该连线，该连线会消失！希望大佬有时间修复一下。

**Comment by Mirror198829** [comment]
> 大佬你好！我在使用该项目的使用发现一个bug： 当以直线方式连接两个Node后，再选中该连线，该连线会消失！希望大佬有时间修复一下。

收到，确实有此bug

**Comment by Mirror198829** [comment]
> 大佬你好！我在使用该项目的使用发现一个bug： 当以直线方式连接两个Node后，再选中该连线，该连线会消失！希望大佬有时间修复一下。

已解决
